class ContactableQuery {
  const ContactableQuery({required this.fields});
  static const contentUri = 'content://com.android.contacts/data/contactables';
  final List<ContactableFields> fields;

  String get queryString {
    return fields.map((e) => e.stringValue).join(',');
  }
}

enum ContactableFields {
  all(''),
  id('_id'),
  accountName('account_name'),
  accountType('account_type'),
  accountTypeAndDataSet('account_type_and_data_set'),
  backupId('backup_id'),
  carrierPresence('carrier_presence'),
  chatCapability('chat_capability'),
  contactChatCapability('contact_chat_capability'),
  contactId('contact_id'),
  contactLastUpdatedTimestamp('contact_last_updated_timestamp'),
  contactPresence('contact_presence'),
  contactStatus('contact_status'),
  contactStatusIcon('contact_status_icon'),
  contactStatusLabel('contact_status_label'),
  contactStatusResPackage('contact_status_res_package'),
  contactStatusTs('contact_status_ts'),
  creationTime('creation_time'),
  customRingtone('custom_ringtone'),
  data1('data1'),
  data10('data10'),
  data11('data11'),
  data12('data12'),
  data13('data13'),
  data14('data14'),
  data15('data15'),
  data2('data2'),
  data3('data3'),
  data4('data4'),
  data5('data5'),
  data6('data6'),
  data7('data7'),
  data8('data8'),
  data9('data9'),
  dataSet('data_set'),
  dataSync1('data_sync1'),
  dataSync2('data_sync2'),
  dataSync3('data_sync3'),
  dataSync4('data_sync4'),
  dataVersion('data_version'),
  dirty('dirty'),
  displayName('display_name'),
  displayNameAlt('display_name_alt'),
  displayNameReverse('display_name_reverse'),
  displayNameSource('display_name_source'),
  groupSourceid('group_sourceid'),
  hasPhoneNumber('has_phone_number'),
  hashId('hash_id'),
  inDefaultDirectory('in_default_directory'),
  inVisibleGroup('in_visible_group'),
  isPrimary('is_primary'),
  isPrivate('is_private'),
  isSim('is_sim'),
  isSuperPrimary('is_super_primary'),
  lastTimeContacted('last_time_contacted'),
  lastTimeUsed('last_time_used'),
  lookup('lookup'),
  mimetype('mimetype'),
  mode('mode'),
  nameRawContactId('name_raw_contact_id'),
  phonebookBucket('phonebook_bucket'),
  phonebookBucketAlt('phonebook_bucket_alt'),
  phonebookLabel('phonebook_label'),
  phonebookLabelAlt('phonebook_label_alt'),
  phoneticName('phonetic_name'),
  phoneticNameStyle('phonetic_name_style'),
  photoFileId('photo_file_id'),
  photoId('photo_id'),
  photoThumbUri('photo_thumb_uri'),
  photoUri('photo_uri'),
  pinned('pinned'),
  preferredPhoneAccountComponentName('preferred_phone_account_component_name'),
  preferredPhoneAccountId('preferred_phone_account_id'),
  rawContactId('raw_contact_id'),
  rawContactIsUserProfile('raw_contact_is_user_profile'),
  resPackage('res_package'),
  secCallBackground('sec_call_background'),
  secCustomAlert('sec_custom_alert'),
  secCustomVibration('sec_custom_vibration'),
  secLed('sec_led'),
  secPreferredSim('sec_preferred_sim'),
  secPreferredVideoCallAccountId('sec_preferred_video_call_account_id'),
  secPreferredVideoCallAccountName('sec_preferred_video_call_account_name'),
  sendToVoicemail('send_to_voicemail'),
  sortKey('sort_key'),
  sortKeyAlt('sort_key_alt'),
  sourceid('sourceid'),
  starred('starred'),
  status('status'),
  statusIcon('status_icon'),
  statusLabel('status_label'),
  statusResPackage('status_res_package'),
  statusTs('status_ts'),
  timesContacted('times_contacted'),
  timesUsed('times_used'),
  version('version');

  const ContactableFields(this.stringValue);
  final String stringValue;
}
